package com.lybxxx.view;

import java.awt.Font;
import java.sql.Connection;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

import com.lybxxx.dao.UserDao;
import com.lybxxx.model.User;
import com.lybxxx.util.ConnectUtil;
import com.lybxxx.util.CheckUtil;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author  lybxxx
 */
public class LoginFrm extends javax.swing.JFrame {
	ConnectUtil connectUtil = new ConnectUtil();
	UserDao userdao = new UserDao();

	/** Creates new form LoginFrm */
	public LoginFrm() {

		Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource) {
				UIManager.put(key, font);
			}
		}

		initComponents();
		this.setLocationRelativeTo(null);
		this.fillTable();
	}

	private void fillTable() {
		User user1 = new User();
		User user2 = new User();
		user1.setUserName("用户");
		user2.setUserName("管理员");
		user1.setId(1 + "");
		user2.setId(2 + "");
		jcb_choose.addItem(user1);
		jcb_choose.addItem(user2);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */

	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		userNameTxt = new javax.swing.JTextField();
		userPasswordTxt = new javax.swing.JPasswordField();
		jb_login = new javax.swing.JButton();
		jb_reset = new javax.swing.JButton();
		jcb_choose = new javax.swing.JComboBox();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("养老院管理系统");
		setResizable(false);

		jLabel1.setFont(new java.awt.Font("宋体", 0, 24));
		jLabel1.setIcon(new ImageIcon(LoginFrm.class.getResource("/images/516550.png")));
		jLabel1.setText("养老院管理系统");

		jLabel2.setIcon(new ImageIcon(LoginFrm.class.getResource("/images/user.png")));
		jLabel2.setText("用户名：");

		jLabel3.setIcon(new ImageIcon(LoginFrm.class.getResource("/images/studengmanage.png")));
		jLabel3.setText("密码：");

		userNameTxt.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				userNameTxtActionPerformed(evt);
			}
		});

		jb_login.setIcon(new ImageIcon(LoginFrm.class.getResource("/images/login.png")));
		jb_login.setText("登录");
		jb_login.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_loginActionPerformed(evt);
			}
		});

		jb_reset.setIcon(new ImageIcon(LoginFrm.class.getResource("/images/reset.gif")));
		jb_reset.setText("重置");
		jb_reset.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_resetActionPerformed(evt);
			}
		});


		jLabel4.setIcon(new ImageIcon(LoginFrm.class.getResource("/images/classmanage.png")));
		jLabel4.setText("登录选项");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
				layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGap(104)
												.addComponent(jb_login, GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
										.addGroup(layout.createSequentialGroup()
												.addGap(103)
												.addGroup(layout.createParallelGroup(Alignment.LEADING)
														.addComponent(jLabel3)
														.addComponent(jLabel2)
														.addComponent(jLabel4))
												.addGap(10)))
								.addGap(42)
								.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addComponent(userNameTxt, GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
										.addComponent(userPasswordTxt, GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
												.addComponent(jb_reset, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jcb_choose, Alignment.LEADING, 0, 111, Short.MAX_VALUE)))
								.addGap(79))
						.addGroup(layout.createSequentialGroup()
								.addContainerGap(139, Short.MAX_VALUE)
								.addComponent(jLabel1)
								.addGap(104))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addGap(21)
								.addGroup(layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(jLabel2)
										.addComponent(userNameTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addGap(26)
								.addGroup(layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(userPasswordTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel3))
								.addGap(26)
								.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel4)
												.addGap(40)
												.addGroup(layout.createParallelGroup(Alignment.BASELINE)
														.addComponent(jb_login)
														.addComponent(jb_reset)))
										.addComponent(jcb_choose, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addContainerGap(43, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
	}


	private void jb_loginActionPerformed(java.awt.event.ActionEvent evt) {
		String userName = userNameTxt.getText();
		String userPassword = new String(userPasswordTxt.getPassword());
		if (CheckUtil.isEmpty(userName)) {
			JOptionPane.showMessageDialog(null, "用户名不能为空！");
			return;
		} else if (CheckUtil.isEmpty(userPassword)) {
			JOptionPane.showMessageDialog(null, "密码不能为空!");
			return;
		}
		User user = new User(userName, userPassword);
		Connection con = null;
		try {
			con = connectUtil.getCon();
			User currentuser = userdao.Login(con, user);
			if (currentuser != null) {
				User user1 = (User) jcb_choose.getSelectedItem();
				String userright = user1.getUserName();
				if ("管理员".equals(userright)) {
					this.dispose();
					MainFrm main = new MainFrm();
					main.setVisible(true);
				} else if ("用户".equals(userright)) {
					this.dispose();
					MainFrm2 main2 = new MainFrm2();
					main2.setVisible(true);
				} else {
					JOptionPane.showMessageDialog(null, "用户名密码错误!");
				}
			}
		} catch (Exception e) {
			JOptionPane.showInternalMessageDialog(null, "登陆失败");
			e.printStackTrace();
		}
	}

	private void jb_resetActionPerformed(java.awt.event.ActionEvent evt) {
		this.userNameTxt.setText("");
		this.userPasswordTxt.setText("");
	}

	private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling cod
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new LoginFrm().setVisible(true);
			}
		});
	}

	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JButton jb_login;
	private javax.swing.JButton jb_reset;
	private javax.swing.JComboBox jcb_choose;
	private javax.swing.JTextField userNameTxt;
	private javax.swing.JPasswordField userPasswordTxt;


}